class BackToNullColumnCandidateAndEvents < ActiveRecord::Migration[5.0]
  def change
 
  	change_column_default :candidates, :article_qualis_a1_total, nil
    change_column_default :candidates, :article_qualis_a2_total, nil
    change_column_default :candidates, :article_qualis_b1_total, nil
    change_column_default :candidates, :article_qualis_b2_total, nil
    change_column_default :candidates, :article_qualis_b3_total, nil
    change_column_default :candidates, :article_qualis_b4_total, nil
    change_column_default :candidates, :article_qualis_b5_total, nil
    change_column_default :candidates, :article_qualis_c_total, nil
    change_column_default :candidates, :articles_total, nil
    change_column_default :candidates, :livros_total, nil
    change_column_default :candidates, :capitulos_de_livros_total, nil
    change_column_default :candidates, :projetos_de_pesquisa_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_a1_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_a2_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_b1_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_b2_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_b3_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_b4_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_b5_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_qualis_c_total, nil
    change_column_default :candidates, :trabalhos_completos_em_anais_de_congresso_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_a1_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_a2_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_b1_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_b2_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_b3_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_b4_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_qualis_c_total, nil
    change_column_default :candidates, :resumos_em_anais_de_congresso_total, nil
    change_column_default :candidates, :bancas_graduacao_total, nil
    change_column_default :candidates, :bancas_mestrado_total, nil
    change_column_default :candidates, :bancas_doutorado_total, nil
    change_column_default :candidates, :bancas_especializacao_total, nil
    change_column_default :candidates, :bancas_total, nil
    change_column_default :candidates, :orientacoes_mestrado_total, nil
    change_column_default :candidates, :orientacoes_doutorado_total, nil
    change_column_default :candidates, :orientacoes_outras_total, nil
    change_column_default :candidates, :orientacoes_total, nil
    change_column_default :candidates, :total_geral, nil
  

  #events

    change_column_default :events, :artigos_qualis_a1, nil
    change_column_default :events, :artigos_qualis_a2, nil
    change_column_default :events, :artigos_qualis_b1, nil
    change_column_default :events, :artigos_qualis_b2, nil
    change_column_default :events, :artigos_qualis_b3, nil
    change_column_default :events, :artigos_qualis_b4, nil
    change_column_default :events, :artigos_qualis_b5, nil
    change_column_default :events, :artigos_qualis_c, nil
    change_column_default :events, :artigos_qualis_a1_max, nil
    change_column_default :events, :artigos_qualis_a2_max, nil
    change_column_default :events, :artigos_qualis_b1_max, nil
    change_column_default :events, :artigos_qualis_b2_max, nil
    change_column_default :events, :artigos_qualis_b3_max, nil
    change_column_default :events, :artigos_qualis_b4_max, nil
    change_column_default :events, :artigos_qualis_b5_max, nil
    change_column_default :events, :artigos_qualis_c_max, nil
    change_column_default :events, :livros, nil
    change_column_default :events, :livros_max, nil
    change_column_default :events, :capitulos_de_livros, nil
    change_column_default :events, :capitulos_de_livros_max, nil
    change_column_default :events, :projetos_de_pesquisa, nil
    change_column_default :events, :projetos_de_pesquisa_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_a1, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_a1_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_a2, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_a2_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b1, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b1_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b2, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b2_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b3, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b3_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b4, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b4_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b5, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_b5_max, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_c, nil
    change_column_default :events, :trabalhos_completos_em_anais_de_congresso_qualis_c_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_a1, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_a1_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_a2, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_a2_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b1, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b1_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b2, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b2_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b3, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b3_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b4, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_b4_max, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_c, nil
    change_column_default :events, :resumos_em_anais_de_congresso_qualis_c_max, nil
    change_column_default :events, :bancas_graduacao, nil
    change_column_default :events, :bancas_graduacao_max, nil
    change_column_default :events, :bancas_mestrado, nil
    change_column_default :events, :bancas_mestrado_max, nil
    change_column_default :events, :bancas_doutorado, nil
    change_column_default :events, :bancas_doutorado_max, nil
    change_column_default :events, :bancas_especializacao, nil
    change_column_default :events, :bancas_especializacao_max, nil
    change_column_default :events, :orientacoes_mestrado, nil
    change_column_default :events, :orientacoes_mestrado_max, nil
    change_column_default :events, :orientacoes_doutorado, nil
    change_column_default :events, :orientacoes_doutorado_max, nil
    change_column_default :events, :orientacoes_outras, nil
    change_column_default :events, :orientacoes_outras_max, nil
   end
end
